import type { Metadata } from 'next'
import LegalPageLayout, { LegalSection } from '@/components/legal/LegalPageLayout'

export const metadata: Metadata = { title: 'Terms of Service' }

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="[FILL-IN: DATE]">
      <p style={{ marginBottom: 24 }}>
        These Terms govern your use of JobScorer, operated by <strong>[FILL-IN: COMPANY LEGAL NAME]</strong>.
        By creating an account you agree to these Terms and to our{' '}
        <a href="/legal/privacy" style={{ color: '#135bec' }}>Privacy Policy</a>.
      </p>

      <LegalSection heading="1. Eligibility">
        <p>You must be at least 18 years old and able to form a binding contract to use JobScorer.</p>
      </LegalSection>

      <LegalSection heading="2. The service">
        <p>JobScorer provides AI-assisted job matching, resume scoring, resume optimization, cover letter
        generation, company research, and project-based skill-building tools.</p>
      </LegalSection>

      <LegalSection heading="3. AI output disclaimer">
        <p>Match scores, recommendations, company research, cover letters, and optimized resumes are
        generated by AI and provided for guidance only. They are not guarantees of accuracy, employment, or
        any outcome. You are responsible for reviewing all content before relying on or submitting it.</p>
      </LegalSection>

      <LegalSection heading="4. Acceptable use">
        <p>You agree not to: submit unlawful content or content you don&apos;t have the right to submit;
        misuse or scrape the service beyond normal use; attempt to bypass rate limits, quotas, or security
        measures; reverse engineer the service; or use JobScorer to violate any third party&apos;s rights.
        We may investigate violations and suspend or terminate accounts that breach this section.</p>
      </LegalSection>

      <LegalSection heading="5. Your content">
        <p>You retain ownership of resumes and data you upload. You grant us a limited license to process
        that content solely to provide the service (scoring, optimization, and related features). You
        warrant that you have the right to submit your content and that doing so does not violate any
        third party&apos;s rights.</p>
      </LegalSection>

      <LegalSection heading="6. Generated output">
        <p>You own the AI-generated output produced for you (optimized resumes, cover letters, scores,
        recommendations) and may use it for any lawful purpose, including job applications. Because this
        output is AI-generated, you are responsible for verifying its accuracy before relying on or
        submitting it — see §3.</p>
      </LegalSection>

      <LegalSection heading="7. Third-party services">
        <p>JobScorer relies on third-party providers to deliver the service, including OpenAI (AI
        processing), Razorpay (payments), Supabase (data storage), and job data providers (SerpAPI,
        JSearch, Apify, Firecrawl). Your use of JobScorer may be subject to those providers&apos; own
        terms where you interact with them directly (for example, Razorpay&apos;s terms when you make a
        payment).</p>
      </LegalSection>

      <LegalSection heading="8. Paid plans, billing, and cancellation">
        <p>
          JobScorer offers both free and paid subscription plans. Paid plans are billed on a recurring
          basis (monthly or annual, as selected at checkout) through Razorpay. By subscribing, you
          authorize us to charge your chosen payment method automatically at the start of each billing
          cycle until you cancel.
        </p>
        <p style={{ marginTop: 12 }}>
          <strong>Cancellation:</strong> You may cancel your subscription at any time from your account
          billing settings. Cancellation takes effect at the end of your current billing period — you keep
          paid-plan access until then, and you will not be charged again afterward.
        </p>
        <p style={{ marginTop: 12 }}>
          <strong>Refunds:</strong> See our{' '}
          <a href="/legal/refund" style={{ color: '#135bec' }}>Refund &amp; Cancellation Policy</a> for
          full details on eligibility and process.
        </p>
        <p style={{ marginTop: 12 }}>
          <strong>Price changes:</strong> We will notify you before any price increase takes effect on
          your next renewal; continuing your subscription after that notice constitutes acceptance of the
          new price.
        </p>
      </LegalSection>

      <LegalSection heading="9. Termination">
        <p>You may delete your account at any time from Settings. We may suspend or terminate accounts
        that violate these Terms. If you have an active paid subscription at termination, §8 and our{' '}
        <a href="/legal/refund" style={{ color: '#135bec' }}>Refund Policy</a> govern any refund.</p>
      </LegalSection>

      <LegalSection heading="10. Disclaimer of warranties">
        <p>THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS, WITHOUT
        WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. JOBSCORER DOES NOT WARRANT THAT THE SERVICE WILL BE
        UNINTERRUPTED, ERROR-FREE, OR THAT AI-GENERATED OUTPUT (INCLUDING MATCH SCORES OR OPTIMIZED
        RESUMES) WILL BE ACCURATE OR RESULT IN EMPLOYMENT.</p>
      </LegalSection>

      <LegalSection heading="11. Limitation of liability">
        <p>To the maximum extent permitted by law, our total liability to you for any claim arising from
        your use of JobScorer is limited to the amount you paid us in the 12 months before the claim
        arose (or [FILL-IN: FREE-TIER LIABILITY CAP AMOUNT] if you are on a free plan). Some jurisdictions
        do not allow the exclusion or limitation of certain warranties or liabilities; in those
        jurisdictions, this limitation applies to the maximum extent permitted by law and may not fully
        apply to you.</p>
      </LegalSection>

      <LegalSection heading="12. Governing law">
        <p>These Terms are governed by the laws of India, with exclusive jurisdiction in the courts of
        [FILL-IN: CITY], India.</p>
      </LegalSection>

      <LegalSection heading="13. Changes to these Terms">
        <p>We may update these Terms from time to time. Material changes will be posted here with a new
        &quot;Last updated&quot; date. Your continued use of JobScorer after changes are posted
        constitutes acceptance of the revised Terms.</p>
      </LegalSection>

      <LegalSection heading="14. Contact">
        <p>Questions about these Terms: <strong>[FILL-IN: SUPPORT EMAIL]</strong></p>
      </LegalSection>

      <p style={{ marginTop: 40, fontSize: '0.8125rem', color: '#94a3b8' }}>
        This page uses generated placeholder text for a legal document and has not been reviewed by a
        lawyer. Replace all [FILL-IN: …] fields and have these Terms reviewed before relying on them.
      </p>
    </LegalPageLayout>
  )
}
