import type { Metadata } from 'next'
import LegalPageLayout, { LegalSection } from '@/components/legal/LegalPageLayout'

export const metadata: Metadata = { title: 'Terms of Service — ResuScore' }

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="[DATE]">
      <p style={{ marginBottom: 24 }}>
        These Terms govern your use of ResuScore, operated by <strong>[COMPANY LEGAL NAME]</strong>.
        By creating an account you agree to these Terms and to our Privacy Policy.
      </p>

      <LegalSection heading="1. Eligibility">
        <p>You must be at least 18 years old and able to form a binding contract to use ResuScore.</p>
      </LegalSection>

      <LegalSection heading="2. The service">
        <p>ResuScore provides AI-assisted job matching, resume scoring, and resume optimization.</p>
      </LegalSection>

      <LegalSection heading="3. AI output disclaimer">
        <p>Match scores, recommendations, company research, and optimized resumes are generated by AI and
        provided for guidance only. They are not guarantees of accuracy, employment, or any outcome. You
        are responsible for reviewing all content before relying on or submitting it.</p>
      </LegalSection>

      <LegalSection heading="4. Acceptable use">
        {/* PASTE GENERATOR BASELINE: acceptable-use prose here */}
        <p>You agree not to misuse the service, upload unlawful content, attempt to breach security, or
        use ResuScore to violate any third party&apos;s rights.</p>
      </LegalSection>

      <LegalSection heading="5. Your content">
        <p>You retain ownership of resumes and data you upload. You grant us a limited license to process
        that content solely to provide the service.</p>
      </LegalSection>

      <LegalSection heading="6. Paid plans (not yet active)">
        <p>ResuScore is currently free to use. Paid subscription plans may be introduced in the future;
        when they are, separate billing, cancellation, and refund terms will apply and will be presented
        before any charge.</p>
      </LegalSection>

      <LegalSection heading="7. Termination">
        <p>You may delete your account at any time. We may suspend or terminate accounts that violate
        these Terms.</p>
      </LegalSection>

      <LegalSection heading="8. Limitation of liability">
        {/* PASTE GENERATOR BASELINE: liability + warranty disclaimer prose here */}
        <p>To the maximum extent permitted by law, ResuScore is provided &quot;as is&quot; without
        warranties, and our liability is limited as described in this section.</p>
      </LegalSection>

      <LegalSection heading="9. Governing law">
        <p>These Terms are governed by the laws of India, with exclusive jurisdiction in the courts of
        [CITY], India.</p>
      </LegalSection>

      <LegalSection heading="10. Contact">
        <p>Questions about these Terms: <strong>[SUPPORT EMAIL]</strong></p>
      </LegalSection>
    </LegalPageLayout>
  )
}
