'use client'

/**
 * Build Plan modal — shown AFTER the user clicks "Generate Optimized Resume"
 * but BEFORE the resume is created. It surfaces job-specific recommendations
 * generated by the "Build Plan Generator" n8n workflow:
 *   1. Certifications worth pursuing for this role
 *   2. Projects to build (each grounded with real public GitHub example repos)
 *   3. Learning paths for the underlying skills
 *
 * Each item shows a gap-derived "+X% interview chances" impact stat and has
 * Accept / Skip / Learn it actions. Accepted items are passed inline into the
 * optimizer and folded into the resume with honest "in progress / planned"
 * framing — we never claim completed credentials the user doesn't have.
 *
 * Design mirrors PasteJobModal: white 640px card, light-blue (#135bec) accents
 * used sparingly, success green (#10b981), fade-up entrance.
 */

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import type { BuildPlan, AcceptedRecommendation } from '@/lib/types'

type Decision = 'accept' | 'skip'

export default function BuildPlanModal({
    buildPlan,
    loading,
    error,
    jobId,
    onConfirm,
    onSkipAll,
    onClose,
}: {
    buildPlan: BuildPlan | null
    loading: boolean
    error: string | null
    jobId: string
    onConfirm: (accepted: AcceptedRecommendation[]) => void
    onSkipAll: () => void
    onClose: () => void
}) {
    const router = useRouter()
    // itemId → decision. Default (absent) is treated as 'skip'.
    const [decisions, setDecisions] = useState<Map<string, Decision>>(new Map())

    // Close on Escape
    useEffect(() => {
        const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
        window.addEventListener('keydown', onKey)
        return () => window.removeEventListener('keydown', onKey)
    }, [onClose])

    const setDecision = (id: string, d: Decision) =>
        setDecisions(prev => {
            const next = new Map(prev)
            // Clicking the active choice again clears it back to skip.
            if (next.get(id) === d) next.delete(id)
            else next.set(id, d)
            return next
        })

    const acceptedCount = [...decisions.values()].filter(d => d === 'accept').length

    function gotoLearning(skill: string) {
        onClose()
        router.push(`/dashboard/learning?jobId=${encodeURIComponent(jobId)}&skill=${encodeURIComponent(skill)}`)
    }

    function collectAccepted(): AcceptedRecommendation[] {
        if (!buildPlan) return []
        const out: AcceptedRecommendation[] = []
        for (const c of buildPlan.certifications) {
            if (decisions.get(c.id) === 'accept') {
                out.push({ type: 'certification', name: c.name, framing_hint: 'in progress' })
            }
        }
        for (const p of buildPlan.projects) {
            if (decisions.get(p.id) === 'accept') {
                out.push({ type: 'project', name: p.name, tech: p.tech, framing_hint: 'in progress' })
            }
        }
        return out
    }

    const hasContent = !!buildPlan && (
        buildPlan.certifications.length > 0 ||
        buildPlan.projects.length > 0 ||
        buildPlan.learning_links.length > 0
    )

    return (
        <>
            <div
                className="bp-overlay"
                onClick={e => { if (e.target === e.currentTarget) onClose() }}
            >
                <div className="bp-card" role="dialog" aria-modal="true" aria-label="Build plan recommendations">
                    <button onClick={onClose} className="bp-close" aria-label="Close">
                        <XIcon />
                    </button>

                    {/* Header */}
                    <div className="bp-header">
                        <div className="bp-header__badge">
                            <SparkIcon />
                        </div>
                        <div>
                            <h2 className="bp-header__title">Boost this resume before you build it</h2>
                            <p className="bp-header__sub">
                                For this exact role, here&apos;s what would move your interview odds the most.
                                Accept what fits — we&apos;ll add it honestly as &ldquo;in progress&rdquo;.
                            </p>
                        </div>
                    </div>

                    {/* Body */}
                    {loading && <LoadingBody />}
                    {!loading && error && <ErrorBody message={error} />}
                    {!loading && !error && !hasContent && <EmptyBody />}

                    {!loading && !error && hasContent && buildPlan && (
                        <div className="bp-body">
                            {/* (a) Certifications */}
                            {buildPlan.certifications.length > 0 && (
                                <Section title="Certifications" count={buildPlan.certifications.length} icon={<CertIcon />}>
                                    {buildPlan.certifications.map(c => (
                                        <ItemCard
                                            key={c.id}
                                            id={c.id}
                                            title={c.name}
                                            meta={c.provider}
                                            body={c.reason}
                                            effort={c.effort}
                                            impactPct={c.impact_pct}
                                            decision={decisions.get(c.id)}
                                            onAccept={() => setDecision(c.id, 'accept')}
                                            onSkip={() => setDecision(c.id, 'skip')}
                                        />
                                    ))}
                                </Section>
                            )}

                            {/* (b) Projects + GitHub example repos */}
                            {buildPlan.projects.length > 0 && (
                                <Section title="Projects to build" count={buildPlan.projects.length} icon={<ProjectIcon />}>
                                    {buildPlan.projects.map(p => (
                                        <ItemCard
                                            key={p.id}
                                            id={p.id}
                                            title={p.name}
                                            body={p.description}
                                            tech={p.tech}
                                            impactPct={p.impact_pct}
                                            decision={decisions.get(p.id)}
                                            onAccept={() => setDecision(p.id, 'accept')}
                                            onSkip={() => setDecision(p.id, 'skip')}
                                            onLearn={(p.learning_skill || p.addresses_gaps?.[0] || p.tech?.[0]) ? () => gotoLearning((p.learning_skill || p.addresses_gaps?.[0] || p.tech?.[0])!) : undefined}
                                        >
                                            {p.example_repos.length > 0 && (
                                                <div className="bp-repos">
                                                    <span className="bp-repos__label">Real examples to learn from</span>
                                                    {p.example_repos.map(r => (
                                                        <a
                                                            key={r.full_name}
                                                            href={r.html_url}
                                                            target="_blank"
                                                            rel="noopener noreferrer"
                                                            className="bp-repo"
                                                        >
                                                            <span className="bp-repo__name">↗ {r.full_name}</span>
                                                            <span className="bp-repo__stars">★ {r.stars.toLocaleString()}</span>
                                                        </a>
                                                    ))}
                                                </div>
                                            )}
                                        </ItemCard>
                                    ))}
                                </Section>
                            )}

                            {/* (c) Learning paths */}
                            {buildPlan.learning_links.length > 0 && (
                                <Section title="Skills to learn" count={buildPlan.learning_links.length} icon={<BookIcon />}>
                                    {buildPlan.learning_links.map(l => (
                                        <div key={l.id} className="bp-item">
                                            <div className="bp-item__main">
                                                <div className="bp-item__head">
                                                    <span className="bp-item__title">{l.skill}</span>
                                                    <ImpactPill pct={l.impact_pct} />
                                                </div>
                                                <p className="bp-item__body">{l.why}</p>
                                            </div>
                                            <div className="bp-item__actions">
                                                <button type="button" className="bp-btn-learn" onClick={() => gotoLearning(l.skill)}>
                                                    Learn it →
                                                </button>
                                            </div>
                                        </div>
                                    ))}
                                </Section>
                            )}
                        </div>
                    )}

                    {/* Footer */}
                    {!loading && (
                        <div className="bp-footer">
                            <button type="button" className="bp-btn-ghost" onClick={onSkipAll}>
                                Skip all &amp; build
                            </button>
                            <button
                                type="button"
                                className="bp-btn-primary"
                                disabled={!!error}
                                onClick={() => onConfirm(collectAccepted())}
                            >
                                {acceptedCount > 0
                                    ? `Build with ${acceptedCount} addition${acceptedCount > 1 ? 's' : ''} →`
                                    : 'Build my resume →'}
                            </button>
                        </div>
                    )}
                </div>
            </div>
            <style>{MODAL_CSS}</style>
        </>
    )
}

// ── Sub-components ────────────────────────────────────────────

function Section({ title, count, icon, children }: {
    title: string; count: number; icon: React.ReactNode; children: React.ReactNode
}) {
    return (
        <section className="bp-section">
            <div className="bp-section__head">
                <span className="bp-section__icon">{icon}</span>
                <h3 className="bp-section__title">{title}</h3>
                <span className="bp-section__count">{count}</span>
            </div>
            <div className="bp-section__items">{children}</div>
        </section>
    )
}

function ItemCard({
    id, title, meta, body, tech, effort, impactPct, decision, onAccept, onSkip, onLearn, children,
}: {
    id: string
    title: string
    meta?: string
    body: string
    tech?: string[]
    effort?: string
    impactPct: number
    decision?: Decision
    onAccept: () => void
    onSkip: () => void
    onLearn?: () => void
    children?: React.ReactNode
}) {
    const accepted = decision === 'accept'
    const skipped = decision === 'skip'
    return (
        <div className={`bp-item${accepted ? ' bp-item--accepted' : ''}`} data-item={id}>
            <div className="bp-item__main">
                <div className="bp-item__head">
                    <span className="bp-item__title">
                        {accepted && <span className="bp-item__check" aria-hidden>✓</span>}
                        {title}
                    </span>
                    <ImpactPill pct={impactPct} />
                </div>
                {(meta || effort) && (
                    <div className="bp-item__meta">
                        {meta && <span>{meta}</span>}
                        {meta && effort && <span className="bp-dot">·</span>}
                        {effort && <span>{effort}</span>}
                    </div>
                )}
                <p className="bp-item__body">{body}</p>
                {tech && tech.length > 0 && (
                    <div className="bp-chips">
                        {tech.map(t => <span key={t} className="bp-chip">{t}</span>)}
                    </div>
                )}
                {children}
            </div>
            <div className="bp-item__actions">
                <button
                    type="button"
                    className={`bp-btn-accept${accepted ? ' is-active' : ''}`}
                    onClick={onAccept}
                >
                    {accepted ? 'Added' : 'Add'}
                </button>
                <button
                    type="button"
                    className={`bp-btn-skip${skipped ? ' is-active' : ''}`}
                    onClick={onSkip}
                >
                    Skip
                </button>
                {onLearn && (
                    <button type="button" className="bp-btn-learn" onClick={onLearn}>
                        Learn it →
                    </button>
                )}
            </div>
        </div>
    )
}

function ImpactPill({ pct }: { pct: number }) {
    return (
        <span className="bp-impact" title="Estimated lift in interview chances, based on the skill gaps this closes">
            +{pct}% interview chances
        </span>
    )
}

function LoadingBody() {
    return (
        <div className="bp-state">
            <div className="bp-spinner" />
            <h3 className="bp-state__title">Building your plan…</h3>
            <p className="bp-state__msg">
                Analyzing this job against your resume and finding real projects to learn from.
                This usually takes 20–60 seconds.
            </p>
        </div>
    )
}

function ErrorBody({ message }: { message: string }) {
    return (
        <div className="bp-state">
            <div className="bp-state__ring bp-state__ring--error">
                <svg width="26" height="26" fill="none" stroke="#DC2626" strokeWidth="2.5" strokeLinecap="round" viewBox="0 0 24 24">
                    <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
                </svg>
            </div>
            <h3 className="bp-state__title">Couldn&apos;t build the plan</h3>
            <p className="bp-state__msg">{message || 'Something went wrong.'} You can still build your resume below.</p>
        </div>
    )
}

function EmptyBody() {
    return (
        <div className="bp-state">
            <div className="bp-state__ring">
                <svg width="26" height="26" fill="none" stroke="#10b981" strokeWidth="2.5" strokeLinecap="round" viewBox="0 0 24 24">
                    <polyline points="20 6 9 17 4 12" />
                </svg>
            </div>
            <h3 className="bp-state__title">You&apos;re in good shape</h3>
            <p className="bp-state__msg">No critical gaps for this role — go ahead and build your resume.</p>
        </div>
    )
}

// ── Icons ─────────────────────────────────────────────────────

function XIcon() {
    return (
        <svg width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" viewBox="0 0 24 24" aria-hidden="true">
            <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
        </svg>
    )
}
function SparkIcon() {
    return (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#135bec" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M12 3v4M12 17v4M3 12h4M17 12h4M5.6 5.6l2.8 2.8M15.6 15.6l2.8 2.8M18.4 5.6l-2.8 2.8M8.4 15.6l-2.8 2.8" />
        </svg>
    )
}
function CertIcon() {
    return (
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <circle cx="12" cy="8" r="6" /><path d="M8.21 13.89L7 22l5-3 5 3-1.21-8.11" />
        </svg>
    )
}
function ProjectIcon() {
    return (
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <polyline points="16 18 22 12 16 6" /><polyline points="8 6 2 12 8 18" />
        </svg>
    )
}
function BookIcon() {
    return (
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" /><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
        </svg>
    )
}

// ── CSS ───────────────────────────────────────────────────────

const MODAL_CSS = `
@keyframes bpFadeUp { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }
@keyframes bpSpin   { to { transform: rotate(360deg); } }

.bp-overlay {
    position: fixed; inset: 0; z-index: 300;
    background: rgba(15,23,42,0.45); backdrop-filter: blur(6px);
    display: flex; align-items: center; justify-content: center;
    padding: 24px;
}
.bp-card {
    background: #fff; border-radius: 22px;
    width: 640px; max-width: 100%;
    max-height: 90vh; display: flex; flex-direction: column;
    box-shadow: 0 28px 70px rgba(15,23,42,0.18);
    animation: bpFadeUp 0.24s ease;
    position: relative;
    font-family: 'Plus Jakarta Sans', 'DM Sans', sans-serif;
    color: #0F172A;
}
.bp-close {
    position: absolute; top: 18px; right: 18px;
    width: 32px; height: 32px; border-radius: 9px;
    background: #F1F5F9; border: 1px solid #E2E8F0;
    color: #64748B; cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    transition: background 0.15s; z-index: 1;
}
.bp-close:hover { background: #E2E8F0; }

.bp-header {
    display: flex; align-items: flex-start; gap: 15px;
    padding: 28px 30px 18px; padding-right: 52px;
    flex-shrink: 0;
}
.bp-header__badge {
    width: 46px; height: 46px; border-radius: 13px;
    background: linear-gradient(135deg, #EFF6FF, #DBEAFE);
    border: 1px solid #BFDBFE;
    display: flex; align-items: center; justify-content: center;
    flex-shrink: 0;
}
.bp-header__title {
    font-size: 20px; font-weight: 800; color: #0F172A;
    font-family: 'Space Grotesk', 'Plus Jakarta Sans', sans-serif;
    letter-spacing: -0.025em; line-height: 1.25; margin: 0 0 6px;
}
.bp-header__sub { font-size: 13.5px; color: #64748B; line-height: 1.6; margin: 0; }

.bp-body {
    overflow-y: auto; padding: 4px 30px 8px;
    display: flex; flex-direction: column; gap: 22px;
}
.bp-section__head {
    display: flex; align-items: center; gap: 9px; margin-bottom: 12px;
}
.bp-section__icon { color: #135bec; display: inline-flex; }
.bp-section__title {
    font-size: 12px; font-weight: 700; color: #475569;
    text-transform: uppercase; letter-spacing: 0.08em; margin: 0;
    font-family: var(--font-mono), 'JetBrains Mono', monospace;
}
.bp-section__count {
    font-size: 11px; font-weight: 700; color: #135bec;
    background: #EFF6FF; border: 1px solid #DBEAFE;
    border-radius: 9999px; padding: 1px 8px;
}
.bp-section__items { display: flex; flex-direction: column; gap: 10px; }

.bp-item {
    display: flex; gap: 14px; justify-content: space-between;
    padding: 15px 16px; border-radius: 13px;
    border: 1.5px solid #E2E8F0; background: #fff;
    transition: border-color 0.15s, background 0.15s, box-shadow 0.15s;
}
.bp-item--accepted {
    border-color: #135bec; background: #F8FAFF;
    box-shadow: 0 0 0 3px rgba(19,91,236,0.08);
}
.bp-item__main { flex: 1; min-width: 0; }
.bp-item__head { display: flex; align-items: flex-start; justify-content: space-between; gap: 10px; }
.bp-item__title {
    font-size: 15px; font-weight: 700; color: #0F172A; line-height: 1.35;
    font-family: 'Space Grotesk', 'Plus Jakarta Sans', sans-serif;
    display: inline-flex; align-items: center; gap: 6px;
}
.bp-item__check { color: #135bec; font-weight: 800; }
.bp-item__meta { font-size: 12px; color: #94A3B8; margin-top: 3px; display: flex; gap: 6px; }
.bp-dot { color: #CBD5E1; }
.bp-item__body { font-size: 13px; color: #475569; line-height: 1.6; margin: 7px 0 0; }

.bp-impact {
    flex-shrink: 0; font-size: 11.5px; font-weight: 700; color: #047857;
    background: #ECFDF5; border: 1px solid #A7F3D0;
    border-radius: 9999px; padding: 3px 10px; white-space: nowrap;
    font-family: var(--font-mono), 'JetBrains Mono', monospace;
}

.bp-chips { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 10px; }
.bp-chip {
    font-size: 11px; font-weight: 600; color: #475569;
    background: #F1F5F9; border-radius: 7px; padding: 3px 8px;
}

.bp-repos {
    margin-top: 12px; padding-top: 12px; border-top: 1px dashed #E2E8F0;
    display: flex; flex-direction: column; gap: 6px;
}
.bp-repos__label {
    font-size: 10.5px; font-weight: 700; color: #94A3B8;
    text-transform: uppercase; letter-spacing: 0.07em;
    font-family: var(--font-mono), 'JetBrains Mono', monospace;
}
.bp-repo {
    display: flex; align-items: center; justify-content: space-between; gap: 10px;
    padding: 7px 11px; border-radius: 9px; text-decoration: none;
    background: #F8FAFC; border: 1px solid #E2E8F0;
    transition: background 0.15s, border-color 0.15s;
}
.bp-repo:hover { background: #EFF6FF; border-color: #BFDBFE; }
.bp-repo__name { font-size: 12.5px; font-weight: 600; color: #135bec; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.bp-repo__stars { font-size: 11.5px; color: #64748B; flex-shrink: 0; font-family: var(--font-mono), 'JetBrains Mono', monospace; }

.bp-item__actions { display: flex; flex-direction: column; gap: 6px; flex-shrink: 0; align-self: center; }
.bp-btn-accept, .bp-btn-skip, .bp-btn-learn {
    padding: 7px 14px; border-radius: 9px; cursor: pointer;
    font-size: 12.5px; font-weight: 700; white-space: nowrap;
    font-family: 'Space Grotesk', 'Plus Jakarta Sans', sans-serif;
    transition: all 0.15s;
}
.bp-btn-accept { background: #EFF6FF; color: #135bec; border: 1.5px solid #BFDBFE; }
.bp-btn-accept:hover { background: #DBEAFE; }
.bp-btn-accept.is-active { background: #135bec; color: #fff; border-color: #135bec; }
.bp-btn-skip { background: #fff; color: #94A3B8; border: 1.5px solid #E2E8F0; }
.bp-btn-skip:hover { color: #64748B; border-color: #CBD5E1; }
.bp-btn-skip.is-active { background: #F1F5F9; color: #475569; border-color: #CBD5E1; }
.bp-btn-learn { background: none; color: #64748B; border: 1.5px solid transparent; padding: 7px 8px; }
.bp-btn-learn:hover { color: #135bec; }

.bp-footer {
    display: flex; justify-content: space-between; align-items: center;
    gap: 10px; padding: 16px 30px 22px; flex-shrink: 0;
    border-top: 1px solid #F1F5F9; margin-top: 4px;
}
.bp-btn-ghost {
    padding: 11px 20px; border-radius: 9999px;
    background: none; border: none; cursor: pointer;
    font-size: 14px; font-weight: 600; color: #64748B;
    font-family: 'Space Grotesk', 'Plus Jakarta Sans', sans-serif;
}
.bp-btn-ghost:hover { color: #0F172A; }
.bp-btn-primary {
    padding: 11px 26px; border-radius: 9999px;
    background: linear-gradient(135deg, #3B82F6, #135bec);
    color: #fff; border: none; cursor: pointer;
    font-size: 14px; font-weight: 700;
    font-family: 'Space Grotesk', 'Plus Jakarta Sans', sans-serif;
    box-shadow: 0 3px 16px rgba(19,91,236,0.35);
    letter-spacing: -0.01em; transition: transform 0.15s, box-shadow 0.15s;
}
.bp-btn-primary:hover:not(:disabled) { transform: translateY(-1px); box-shadow: 0 6px 20px rgba(19,91,236,0.45); }
.bp-btn-primary:disabled { background: #E2E8F0; color: #94A3B8; cursor: not-allowed; box-shadow: none; }

.bp-state {
    padding: 36px 30px 44px; display: flex; flex-direction: column;
    align-items: center; gap: 16px; text-align: center;
}
.bp-spinner {
    width: 40px; height: 40px; border-radius: 50%;
    border: 3.5px solid #DBEAFE; border-top-color: #135bec;
    animation: bpSpin 0.8s linear infinite;
}
.bp-state__ring {
    width: 60px; height: 60px; border-radius: 50%;
    background: #ECFDF5; border: 2px solid #A7F3D0;
    display: flex; align-items: center; justify-content: center;
}
.bp-state__ring--error { background: #FEF2F2; border-color: #FECACA; }
.bp-state__title {
    font-size: 18px; font-weight: 800; color: #0F172A; margin: 0;
    font-family: 'Space Grotesk', 'Plus Jakarta Sans', sans-serif; letter-spacing: -0.02em;
}
.bp-state__msg { font-size: 13.5px; color: #64748B; line-height: 1.65; margin: 0; max-width: 420px; }

@media (max-width: 640px) {
    .bp-card { border-radius: 18px; }
    .bp-header { padding: 22px 20px 16px; padding-right: 46px; }
    .bp-body { padding: 4px 20px 8px; }
    .bp-footer { padding: 14px 20px 18px; }
    .bp-item { flex-direction: column; }
    .bp-item__actions { flex-direction: row; align-self: stretch; }
}
`
